#!/usr/bin/env node
/**
 * Phase 085 — requirements traceability.
 *
 * Real, runnable traceability check: parses docs/GOAL_COMPLETION_MATRIX.md, and
 * for every phase row extracts the source/doc/test artifacts named in its
 * evidence column, then verifies each referenced path actually exists on disk.
 *
 * This turns the completion matrix into a checkable claim: a phase marked
 * "Implemented" whose cited files are missing is flagged. Writes a report to
 * docs/TRACEABILITY.md and exits non-zero if any cited artifact is missing
 * (so it can be a CI/stabilization gate — Phase 089).
 *
 * Usage: node scripts/traceability.mjs [--write]
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MATRIX = join(ROOT, 'docs', 'GOAL_COMPLETION_MATRIX.md');
const OUT = join(ROOT, 'docs', 'TRACEABILITY.md');

// Path-like tokens we treat as citeable artifacts. The filename portion is
// greedy and includes dots so multi-extension paths (e.g. foo.smoke.test.ts)
// are captured whole; a trailing sentence period is trimmed after matching.
const PATH_RE = /\b((?:server|docs|tests|shared|src|src-main|scripts|\.github)\/[A-Za-z0-9_./-]*[A-Za-z0-9_-]\.[A-Za-z0-9]+)/g;
const ROW_RE = /^\|\s*(\d{3})\s*\|\s*(.+?)\s*\|\s*\*\*(.+?)\*\*\s*\|\s*(.+?)\s*\|$/;

function main() {
  if (!existsSync(MATRIX)) {
    console.error(`traceability: matrix not found at ${MATRIX}`);
    process.exit(2);
  }
  const lines = readFileSync(MATRIX, 'utf8').split(/\r?\n/);
  const rows = [];
  for (const line of lines) {
    const m = ROW_RE.exec(line);
    if (!m) continue;
    const [, phase, title, status, evidence] = m;
    const cited = [...evidence.matchAll(PATH_RE)].map((x) => x[1]);
    // De-dup while preserving order.
    const unique = [...new Set(cited)];
    const missing = unique.filter((p) => !existsSync(join(ROOT, p)));
    rows.push({ phase, title, status, cited: unique, missing });
  }

  const withCites = rows.filter((r) => r.cited.length > 0);
  const broken = rows.filter((r) => r.missing.length > 0);
  const implementedNoCite = rows.filter(
    (r) => /Implemented/i.test(r.status) && r.cited.length === 0,
  );

  const report = [];
  report.push('# Requirements Traceability (Phase 085)');
  report.push('');
  report.push('> Generated by `node scripts/traceability.mjs`. Do not edit by hand.');
  report.push('');
  report.push(
    `Parsed **${rows.length}** phase rows from the completion matrix. ` +
      `**${withCites.length}** cite at least one concrete artifact; ` +
      `**${broken.length}** cite a path that does **not** exist on disk.`,
  );
  report.push('');
  report.push('## Broken references (cited but missing)');
  report.push('');
  if (broken.length === 0) {
    report.push('None — every artifact cited in the matrix exists. ✅');
  } else {
    report.push('| Phase | Status | Missing artifact(s) |');
    report.push('|---|---|---|');
    for (const r of broken) {
      report.push(`| ${r.phase} | ${r.status} | ${r.missing.join('<br>')} |`);
    }
  }
  report.push('');
  report.push('## Phase → artifact map (rows citing files)');
  report.push('');
  report.push('| Phase | Title | Status | Verified artifacts |');
  report.push('|---|---|---|---|');
  for (const r of withCites) {
    const marks = r.cited
      .map((p) => `${existsSync(join(ROOT, p)) ? '✅' : '❌'} \`${p}\``)
      .join('<br>');
    report.push(`| ${r.phase} | ${r.title} | ${r.status} | ${marks} |`);
  }
  report.push('');
  report.push('## Implemented rows with no cited artifact (review for over-claim)');
  report.push('');
  if (implementedNoCite.length === 0) {
    report.push('None — every "Implemented" row cites a concrete artifact.');
  } else {
    report.push(
      'These are marked Implemented but cite no file. Many are process/own-deliverable ' +
        'phases (docs, rules) — listed here for honest review, not as automatic failures.',
    );
    report.push('');
    report.push('| Phase | Title |');
    report.push('|---|---|');
    for (const r of implementedNoCite) report.push(`| ${r.phase} | ${r.title} |`);
  }
  report.push('');

  const text = report.join('\n');
  const write = process.argv.includes('--write');
  if (write) {
    writeFileSync(OUT, text + '\n');
    console.log(`traceability: wrote ${OUT}`);
  } else {
    console.log(text);
  }

  console.error(
    `traceability: ${rows.length} rows, ${withCites.length} cited, ${broken.length} broken.`,
  );
  process.exit(broken.length === 0 ? 0 : 1);
}

main();
